# Lecture 3

## Dictionary

In [1]:
my_dict= {"Name": "Akash", "Age":20}
my_dict

{'Name': 'Akash', 'Age': 20}

In [2]:
my_dict["Age"] = 21
my_dict

{'Name': 'Akash', 'Age': 21}

In [3]:
my_dict.items()

dict_items([('Name', 'Akash'), ('Age', 21)])

In [4]:
my_dict.keys()

dict_keys(['Name', 'Age'])

In [5]:
my_dict.values()

dict_values(['Akash', 21])

## Conditional statements

### If else statements

In [6]:
#if

a=10
b=5

if a==10:
    print(b)

5


In [7]:
#if...else

a=7
b=5

if a==10:
    print(b)
else:
    print(a)

7


In [8]:
#elif

a=7
b=5

if a==10:
    print(b)
elif a==7:
    print(a+b)
else:
    print(a)

12


## Iterative statements

### for loop

In [9]:
n=10
for i in range(n):          #range(start, stop, stepsize)
    print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 

In [10]:
#Iterate through list
my_list = ["Akash", "Vishal", "Raju", "Ram"]
for i in my_list:
    print(i, end=" ")

Akash Vishal Raju Ram 

### while loop

In [11]:
n=10
i=0
while i<n:
    print(i, end=" ")
    i+=1

0 1 2 3 4 5 6 7 8 9 

In [12]:
#while loop with continue

n=10
i=0
while i<n:
    if i==6:
        i+=1
        continue
    print(i, end=" ")
    i+=1

0 1 2 3 4 5 7 8 9 

In [13]:
#while loop with break

n=10
i=0
while i<n:
    if i==6:
        i+=1
        break
    print(i, end=" ")
    i+=1

0 1 2 3 4 5 

In [14]:
#while loop with pass

n=10
i=0
while i<n:
    if i==6:
        i+=1
        pass
    print(i, end=" ")
    i+=1

0 1 2 3 4 5 7 8 9 

## Functions

### User defined functions

In [15]:
#Prime number check function

def isprime(n):
    for i in range(2,n//2):
        if(n%i==0):
            return False
    return True

n=7
print(isprime(7))

True


In [16]:
#Circle area function

import math
def circ_area(r):
    return math.pi*r*r

r = float(input("Enter the radius of your circle: "))
print("Area of your circle is ", circ_area(r))

Enter the radius of your circle: 3
Area of your circle is  28.274333882308138


In [17]:
#Rectange area function

def rect_area(l, b):
    return l*b

l = float(input("Enter the length of your rectangle: "))
b = float(input("Enter the breadth of your rectangle: "))
print("Area of your rectange is ", rect_area(l, b))

Enter the length of your rectangle: 3
Enter the breadth of your rectangle: 4
Area of your rectange is  12.0


In [18]:
#BMI calculation function

def bmi(w, h):
    return w/(h*h)

w = float(input("Enter your weight(in kg): "))
h = float(input("Enter your height(in m): "))
print("Your BMI is ", bmi(w, h))

Enter your weight(in kg): 60
Enter your height(in m): 1.75
Your BMI is  19.591836734693878


### Builtin functions

In [19]:
a= range(1, 11)
print(len(a))

10


### Lambda functions

In [20]:
#One argument

x = lambda a:a+10
print(x(10))

20


In [21]:
#Two argument

x = lambda a,b:a+b
print(x(10, 20))

x = lambda a,b:a*b
print(x(10, 20))

30
200


In [22]:
#Three argument

x = lambda a,b,c:a+b+c
print(x(10, 20, 30))

60


## Numpy

In [23]:
#loading packages
import numpy as np

In [24]:
#creating an array

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [25]:
#checking dimension of array
print(arr.ndim)

1


In [26]:
#creating an 2D array

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [27]:
#checking dimension of array
print(arr.ndim)

2


In [28]:
#creating an 3D array

arr = np.array([[[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]]])
print(arr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [29]:
#checking dimension of array
print(arr.ndim)

3


### Zero and one array

In [30]:
#zero array
a= np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [31]:
#one array
a= np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [32]:
#increasing dimensions

a= np.zeros([3, 3, 4])      #([kD, ..., 3D, 2D, 1D])
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [33]:
type(arr)

numpy.ndarray

### Functions of numpy

In [34]:
arr = np.array([10,20,30,40,50])

print(arr.size)

5


In [35]:
arr[4].dtype

dtype('int64')

In [36]:
#Find index position of maximum element in array by using argmax()

print(arr)
print(arr.argmax())

[10 20 30 40 50]
4


In [37]:
#Find index position of minimum element in array by using argmin()

print(arr)
print(arr.argmin())

[10 20 30 40 50]
0


In [38]:
# arange function

a = np.arange(15) #end
b = np.arange(0, 15) #start, end
c = np.arange(0, 15, 2) #start, end, step
print(a)
print(b)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  2  4  6  8 10 12 14]


In [39]:
# Reshape function

a = np.arange(12)
a = a.reshape(3,4)
print(a)    #Multiples of 12 ex: 1,12  3,4  4,3  etc.

# Create 3D array using reshape
a = a.reshape(3,2,2)   #Multiples of 12 ex: 1,12  3,4  4,3  etc.
print(a) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [40]:
# shape function
print(a.shape)

(3, 2, 2)


In [41]:
# max function
print(a.max())

11


In [42]:
# min function
print(a.min())

0


### Slicing

In [43]:
arr = np.array([10,20,30,40,50])

print(arr[1:3])

[20 30]


In [44]:
arr = [10,20,30,40,50]

print(arr[2:5])

[30, 40, 50]


In [45]:
arr[::-1]

[50, 40, 30, 20, 10]

### Exercise

In [46]:
arr = np.array([[1,2],[2,3],[3,4],[4,5]])
print(arr)

[[1 2]
 [2 3]
 [3 4]
 [4 5]]


In [47]:
print(arr.size)
print(arr.ndim)

8
2
